require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.lualine-config"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.telescope"
require "user.autopairs"
require "user.nvimtree"
require "user.colorscheme"
require "user.null-ls"
require "user.toggleterm"


