require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.lualine-config"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.telescope"
vim.cmd[[colorscheme tokyonight]]
